# Generated by Django 2.2.9 on 2020-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorders',
            name='title',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
